# Generated by Django 3.0.6 on 2020-05-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_auto_20200518_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlink',
            name='oid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(default=1589829733.429342),
        ),
    ]
