# Generated by Django 3.0.6 on 2020-05-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0004_auto_20200518_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(default=1589830492.925473),
        ),
        migrations.AlterField(
            model_name='serveripaddress',
            name='ping_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
