# Generated by Django 3.0.6 on 2020-05-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0005_auto_20200518_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serveripaddress',
            old_name='ping_status',
            new_name='pingstatus',
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(default=1589830639.1223724),
        ),
    ]
