# Generated by Django 3.0.6 on 2020-05-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0006_auto_20200518_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(default=1589830772.8707526),
        ),
        migrations.AlterField(
            model_name='serverlink',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
