# Generated by Django 3.0.6 on 2020-05-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0007_auto_20200518_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(default=1589992407.5961354),
        ),
        migrations.AlterField(
            model_name='serveripaddress',
            name='pingstatus',
            field=models.CharField(blank=True, default='Passed', max_length=20, null=True),
        ),
    ]
