# Generated by Django 3.0.6 on 2020-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0008_auto_20200520_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibparameter',
            name='correctthresholdvalue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='mib_parameter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='mibtype',
            field=models.CharField(blank=True, default='statechange', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='stateduration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(blank=True, default=1589995820.7161195, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='thresholdvalue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='transition_statetime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
