# Generated by Django 3.0.6 on 2020-05-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0010_auto_20200525_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='mibparameter',
            name='oid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
