# Generated by Django 3.0.6 on 2020-05-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0011_mibparameter_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlink',
            name='testname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
