# Generated by Django 3.0.6 on 2020-05-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0012_serverlink_testname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverlink',
            name='testname',
        ),
    ]
