# Generated by Django 3.0.6 on 2020-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0014_serverlink_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlink',
            name='colour',
            field=models.CharField(blank=True, default='Passed', max_length=200, null=True),
        ),
    ]
