# Generated by Django 3.0.6 on 2020-06-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0015_auto_20200610_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveripaddress',
            name='pingstatus',
            field=models.BooleanField(blank=True, default=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serverlink',
            name='colour',
            field=models.CharField(blank=True, default='red', max_length=200, null=True),
        ),
    ]
