# Generated by Django 3.0.6 on 2020-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0017_auto_20200610_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='mibparameter',
            name='stateduration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(blank=True, default=1592508042.618341, null=True),
        ),
        migrations.AddField(
            model_name='mibparameter',
            name='transition_statetime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
