# Generated by Django 3.0.6 on 2020-06-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0018_auto_20200618_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='mibparameter',
            name='email',
            field=models.BooleanField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='email_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(blank=True, default=1592590442.3622372, null=True),
        ),
    ]
