# Generated by Django 3.0.6 on 2020-09-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0019_auto_20200619_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(blank=True, default=1599607501.5903656, null=True),
        ),
    ]
