# Generated by Django 3.1.3 on 2020-11-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0020_auto_20200908_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(blank=True, default=1605640718.0374823, null=True),
        ),
    ]
