# Generated by Django 3.1.3 on 2020-12-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0021_auto_20201117_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(blank=True, default=1606949614.789398, null=True),
        ),
        migrations.CreateModel(
            name='StateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mib_change', models.DateTimeField(verbose_name='date modified')),
                ('mib_status', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('parent_mib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor_app.mibparameter')),
            ],
        ),
    ]
