# Generated by Django 3.1.3 on 2020-12-03 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0022_auto_20201202_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mibparameter',
            name='statetimestart',
            field=models.FloatField(blank=True, default=1607005104.382728, null=True),
        ),
        migrations.AlterField(
            model_name='staterecord',
            name='mib_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
